name: Deploy to DockerHub and Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Push to Docker Hub + Redeploy on Railway
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clona el repo
      - uses: actions/checkout@v3

      # Paso 2: Configura Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Inicia sesión en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Paso 4: Construye y sube la imagen
      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/reservaplus:latest

      # Paso 5: Redeploy en Railway
      - name: Redeploy on Railway
        run: |
          curl -X POST https://backboard.railway.app/graphql \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}" \
          -d '{"query":"mutation { deployService(id: \"${{ secrets.RAILWAY_SERVICE_ID }}\") { id } }"}'
