name: Deploy to DockerHub and Railway

on:
  push:
    branches: [ main ]

jobs:
  dockerhub:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/reservaplus:latest

  railway:
    name: Deploy to Railway
    needs: dockerhub
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN:      ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT:    ${{ secrets.RAILWAY_PROJECT }}    # p.ej. project_abcd1234
      RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }} # p.ej. srv_efgh5678
    steps:
      - uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli@3.14.0

      - name: Deploy to Railway
        run: |
          railway up \
            --project $RAILWAY_PROJECT \
            --service $RAILWAY_SERVICE_ID \
            --detach
