name: Deploy to DockerHub and Railway
on:
  push:
    branches: ["main"]

jobs:
  dockerhub:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/reservas:latest .
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/reservas:latest

  railway:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: dockerhub
    steps:
      - uses: actions/checkout@v3
      - name: Install Railway CLI
        run: npm install -g railway
      - name: Railway Login
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}
      - name: Link Railway Project
        run: railway link ${{ secrets.RAILWAY_PROJECT }}
      - name: Deploy to Railway
        run: railway up

